import { Box, Flex, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import Header from "./Header/Header";

type Props = {
  children: React.ReactNode;
};

const Layout: React.FC<Props> = ({ children }) => (
  <>
    <Head>
      <title>Sellit.ng</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Box minHeight="100vh">
      <Header />

      <Box as="main">{children}</Box>

      <Box as="footer"></Box>
    </Box>
  </>
);

export default Layout;
